//! Auto-generated skills module.
//! Skills are Rust utility functions generated by the evolution cycle.
//! This file is automatically updated by the evolution engine.
//! Do not edit manually — changes will be overwritten.

pub mod to_title_case;
pub mod is_alphanumeric;
